color: rose
description: null
fieldLayouts:
  b007a5b3-cca7-4207-b036-fe7d673b3282:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-16T15:49:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4266eca9-64f2-411b-bb90-38fa915fdb2f # Home Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d7aa49ba-8801-4b42-a863-d4f4d5e089e7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-16T15:50:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bea879fe-8aa8-489a-a916-d3e87e9501d3 # Featured Projects
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d3c8fb9-7db3-43b7-96bc-4cbc85f7382b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T15:13:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 82c07441-e3c0-44ed-9670-0492a1afb8e3 # Accordions
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 008da413-b543-444a-964e-1ecbaeef8082
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-17T16:03:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e97e691f-d62b-4d4c-a7e8-c12bcad7ebdc # Logos
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6980f80a-4e35-4fb1-be6b-5e39377d8479
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0456b700-882a-41a2-9d21-d701e637a1dd
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-10T15:19:08+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 32c1a0e7-223d-4621-a973-a36daf057365 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8594cba3-6e5d-4d27-a7af-6f2dad41d48c
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 3e0b4769-e640-4521-8b20-df43b2c736bb
        userCondition: null
handle: homePage
hasTitleField: false
icon: null
name: 'Home Page'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
