color: null
description: null
fieldLayouts:
  482aeafe-6878-4795-8c4f-cf1a421233ce:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-30T02:33:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ef204d2f-becd-44e1-a30c-d6066aae69e1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-30T02:34:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b4d03c8-7715-46d6-b73f-c0c2b0d1827f # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9218be31-ab72-4507-832a-2f8c28a770be
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 18ed98d4-041e-45b4-be39-2ce22bd730f8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-30T02:34:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f5c8f0a-945f-4282-b103-4656d640ec1a # Spacing Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32bcec16-9caf-448b-9f4a-5aa985e521f7
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-30T02:34:35+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 315e419f-401e-4161-a287-7cfd8f011a58 # Spacing Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffb93f50-5aa2-4a83-8cbf-c51d6d7a518b
            userCondition: null
            warning: null
            width: 50
        name: Style
        uid: 8b1783bc-2f6b-4d07-811d-89cbf15872db
        userCondition: null
handle: largeText
hasTitleField: true
icon: null
name: 'Large Text'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
