color: null
description: null
fieldLayouts:
  2d37d528-f11c-44de-8bd9-35f378a4247e:
    cardThumbAlignment: start
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-17T15:11:58+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9daba4be-465f-45a9-8f39-003ab04ac199 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a226aa1-7a02-433e-bd0b-bd2034cf3f61
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f58c453b-60f0-482a-83e3-1d57571e0580
        userCondition: null
handle: logo
hasTitleField: false
icon: null
name: Logo
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
