color: null
description: null
fieldLayouts:
  6a7c8e69-bed5-4857-bb1a-2ed32754d747:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-17T16:02:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4c7b3f13-cdd7-42a8-adca-fed91d9d075b # Logos
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a36696d8-c676-4817-91ea-f61a7c16c098
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8eee4afe-6a1f-4430-a3ad-bd54d879736d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-17T16:02:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f5c8f0a-945f-4282-b103-4656d640ec1a # Spacing Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8bda5f8-8973-43f1-ae2b-5cfb724740e1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-17T16:02:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 315e419f-401e-4161-a287-7cfd8f011a58 # Spacing Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 767a5364-5f53-4957-9a8d-4195b3a9fea5
            userCondition: null
            warning: null
            width: 50
        name: Style
        uid: b0aff972-3362-4fc3-9ba8-10f51394b774
        userCondition: null
handle: logos
hasTitleField: false
icon: null
name: Logos
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
