color: lime
description: null
fieldLayouts:
  002009ea-2934-4d1e-acd9-40ee3ccc636f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-11T01:59:06+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e6a78e06-8f70-4549-8235-521f0d1dfb4b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-11T02:01:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fa6d2ccc-d2b4-43a3-b23c-989309e499f1 # Projects
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc8d468e-e7bd-4663-b0dd-d6b835c901f8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c3549435-320c-4991-ae50-c3053ef92f34
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-11T02:01:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f5c8f0a-945f-4282-b103-4656d640ec1a # Spacing Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d2226e5-3961-42c2-82ea-5f2d7cf2d9a6
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-11T02:01:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 315e419f-401e-4161-a287-7cfd8f011a58 # Spacing Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ee0a5b0-f67d-4f53-8115-4bfed9201cc9
            userCondition: null
            warning: null
            width: 50
        name: Style
        uid: 9c2a86b3-4e4a-46a0-b527-c34e3647916f
        userCondition: null
handle: relatedProjects
hasTitleField: true
icon: diagram-project
name: 'Related Projects'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
