color: null
description: null
fieldLayouts:
  b05fc71f-e7ff-4683-b04d-3280e3a40828:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-30T02:27:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 65a22dab-b6e6-4bd0-b6c9-f4ae754b65b6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-30T02:28:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fa6d2ccc-d2b4-43a3-b23c-989309e499f1 # Projects
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e1771444-e5f8-490a-99de-223a0f7d09e2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e8877a88-9070-411b-8d77-99a60c357f21
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-30T02:30:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f5c8f0a-945f-4282-b103-4656d640ec1a # Spacing Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84d6b027-d9d2-4f26-a941-5fd182269e39
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-30T02:30:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 315e419f-401e-4161-a287-7cfd8f011a58 # Spacing Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4a5fe56-2787-4703-9c25-9c726b311c62
            userCondition: null
            warning: null
            width: 50
        name: Style
        uid: 131a6f3b-2a96-4b19-aadf-cf027bcfbed6
        userCondition: null
handle: selectedProjects
hasTitleField: true
icon: null
name: 'Selected Projects'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
