color: rose
description: null
fieldLayouts:
  22689be4-709b-4429-8beb-271f70335d3d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-10T15:14:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 330ef4b8-8663-48d9-acb7-660adb93013f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e93d04d8-e103-44cd-b144-5dec45b89a39
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-10T15:20:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 32c1a0e7-223d-4621-a973-a36daf057365 # SEO
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f38d61cc-2d78-45b5-9dc6-ff47d9d07776
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: a5bea87f-febd-4364-ad96-b473a90ae2b0
        userCondition: null
handle: servicesPage
hasTitleField: true
icon: null
name: 'Services Page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
