color: null
description: null
fieldLayouts:
  5750a890-3d82-4768-a4ad-3530efd752a2:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:f7524321-4b20-4244-8d1c-6cc8b3be94e3'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-24T16:04:14+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f6c073bd-e8af-4129-a951-b421f334ac52
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T16:06:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b4d03c8-7715-46d6-b73f-c0c2b0d1827f # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7524321-4b20-4244-8d1c-6cc8b3be94e3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T16:06:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a607ab73-8761-41ed-8c48-cda27c9bc0b9 # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60b29cf2-5c94-44fb-b0fc-f09e4bd8d736
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T16:06:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5d289450-50a9-49a7-9070-3dd8b2c3003d # Services
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 093ceb77-12eb-4cce-ab92-df5081895d49
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T16:06:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9daba4be-465f-45a9-8f39-003ab04ac199 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 051b0873-88b2-45f5-9bab-170239bfd278
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f0be4458-902c-4516-b975-085cf7c574c7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-24T16:07:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 982e09db-7613-4a49-80ca-8e68f2f97249 # Background Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0853bdde-c32d-4b35-9a61-6596815f5433
            userCondition: null
            warning: null
            width: 100
        name: Style
        uid: d42aba72-2e02-4dae-b61c-7680e3e5cac7
        userCondition: null
handle: serviceCards
hasTitleField: true
icon: null
name: 'Service Cards'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
