color: null
description: null
fieldLayouts:
  396bf9cb-8df7-428c-b9d6-0d102d29c0c9:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:1598d847-5edc-4801-a82d-7abcf835e08e'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-24T15:16:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f1349abc-be32-4125-88e8-7ced6117345c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T15:17:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 617641f8-b484-43e1-b424-cbd1d07938ce # Job Role
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1598d847-5edc-4801-a82d-7abcf835e08e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T15:17:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9daba4be-465f-45a9-8f39-003ab04ac199 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5cf7598d-ec9e-436d-bfd7-ed618a03b9f2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T15:17:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c4840206-fedb-4bac-927b-55c73db6de49 # LinkedIn
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 62cb8cab-19c6-4951-b8fe-ccfe4309dd69
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cf559258-2175-4a21-8b3d-ff10b074c8fa
        userCondition: null
handle: teamMember
hasTitleField: true
icon: null
name: 'Team Member'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
