color: pink
description: null
fieldLayouts:
  83aa6815-c4f2-49ab-94fd-1dcf91dd9465:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:12933116-085f-423a-9b32-7f61c33179f8'
      - 'layoutElement:202594ad-ec79-4ec2-aacd-5cdc297af6b0'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-11T01:56:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Author
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e831d8f1-d347-4244-9e7b-063c84d0f2f1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-11T01:57:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6beb3f07-e677-4659-b409-2176f97b9fa6 # Client Name
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12933116-085f-423a-9b32-7f61c33179f8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-11T01:57:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: b94200d6-cc19-453f-a8ca-4f1dd462e005 # Testimonial
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 202594ad-ec79-4ec2-aacd-5cdc297af6b0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-11T03:18:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fbbd67cd-d950-4703-8997-71104696f7f1 # Project Colour
            handle: null
            includeInCards: false
            instructions: null
            label: Colour
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32927f3a-6d5d-4fcb-aaba-a092f3dfcb24
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-30T02:58:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: e7172cdd-3855-4eb8-b1f5-5ad3ea8f3a61 # Text Style
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4267f6f-1f94-4eab-a7c6-894a567b3a5f
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 7564d953-3d3c-49ec-80a2-2b49cc99bcd3
        userCondition: null
      -
        elementCondition: null
        name: Style
        uid: 0396910b-b73c-4964-ac93-e29843eafdbd
        userCondition: null
handle: testimonials
hasTitleField: true
icon: null
name: Testimonials
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
