color: null
description: null
fieldLayouts:
  d385e4da-a3c2-49ce-9955-0e46f296c741:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-24T16:10:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 70ad0519-17a7-4d06-87fa-7cd9c80b634c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T16:12:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 54e89074-690f-4470-acd5-39367985c214 # Keyline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37ca8e63-e632-4bb2-b321-bb709cea974d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T16:12:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a607ab73-8761-41ed-8c48-cda27c9bc0b9 # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4e156cb-bcd0-4a7c-acdc-d0786f5482c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-24T16:12:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9daba4be-465f-45a9-8f39-003ab04ac199 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 477e13b0-f749-4a02-bdb7-8cdd713f7be5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 723319d5-3f0e-4f59-9718-ad7c2330116e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-24T16:12:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f5c8f0a-945f-4282-b103-4656d640ec1a # Spacing Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 695b34b0-1b9c-40ba-a694-a52740a4fdfb
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-24T16:12:03+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 315e419f-401e-4161-a287-7cfd8f011a58 # Spacing Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7875ab9-56d2-460a-b55b-304b23f6db1a
            userCondition: null
            warning: null
            width: 50
        name: Style
        uid: 9e12b5b4-fb89-4722-8a4a-973cbc3a5dde
        userCondition: null
handle: textImage
hasTitleField: true
icon: null
name: 'Text & Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
