color: lime
description: null
fieldLayouts:
  915a5dd6-f90f-4536-ba75-ccb2eeb5c38a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-11T01:55:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 836b384f-2c07-4a35-bc13-596e178be7ce # Video
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08747704-425f-457a-8be3-defffe3a41ac
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 133c4f86-bde7-48a7-8eed-09453a50b748
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-11T01:55:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3f5c8f0a-945f-4282-b103-4656d640ec1a # Spacing Top
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3eedee23-f5b0-48dd-9fe9-4c1d861fa70c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-09-11T01:55:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 315e419f-401e-4161-a287-7cfd8f011a58 # Spacing Bottom
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ed5fc3c-13c5-49a2-9f0b-71a8f6b0c5cb
            userCondition: null
            warning: null
            width: 50
        name: Style
        uid: c3641ed0-a9f2-41af-9720-c4d7465a42fd
        userCondition: null
handle: video
hasTitleField: false
icon: video
name: Video
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
