altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fcbf3355-74ec-4d14-b871-106a40c1366a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-11T01:46:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: bac0d9e5-d341-4e13-9233-2b5b96da8262
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1c20da32-5c07-480e-95a3-cf3b45023239
        userCondition: null
fs: local
handle: default
name: Default
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
