columnSuffix: null
handle: featuredProjects
instructions: null
name: 'Featured Projects'
searchable: false
settings:
  fieldLayouts:
    __assoc__:
      -
        - b90611b9-9214-44d8-8ed5-2f9984f29a37
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    1:
                      - uid
                      - 50aa365e-32dd-4c98-a183-b982f9689977
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - true
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-09-16T15:50:17+00:00'
                            11:
                              - uid
                              - 83c3384d-0894-4294-be34-166eb485b93b
                            14:
                              - fieldUid
                              - d1152384-d38a-4a7d-9196-940e2b001cba # Heading
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - true
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-09-16T15:50:17+00:00'
                            11:
                              - uid
                              - c4fa8a3f-8b34-4c8c-999c-47d8c575abb3
                            14:
                              - fieldUid
                              - fa6d2ccc-d2b4-43a3-b23c-989309e499f1 # Projects
            3:
              - cardThumbAlignment
              - end
  viewMode: grouped
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
