columnSuffix: null
handle: heroSimple
instructions: null
name: 'Hero (Simple)'
searchable: false
settings:
  fieldLayouts:
    __assoc__:
      -
        - e14f70b8-cd0a-4254-a0d0-1431a0d4d2a8
        -
          __assoc__:
            0:
              - tabs
              -
                -
                  __assoc__:
                    0:
                      - name
                      - Content
                    1:
                      - uid
                      - 83dfd580-e741-43b8-96eb-fd1d6cdf1a8b
                    4:
                      - elements
                      -
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - true
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-09-22T11:20:54+00:00'
                            11:
                              - uid
                              - f0ea4082-ca29-43df-a8e5-b7fef90e9bd3
                            14:
                              - fieldUid
                              - d1152384-d38a-4a7d-9196-940e2b001cba # Heading
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 100
                            10:
                              - dateAdded
                              - '2025-09-22T11:20:54+00:00'
                            11:
                              - uid
                              - 7a164f1e-19ea-4c25-adcb-88711151a0c8
                            14:
                              - fieldUid
                              - 54e89074-690f-4470-acd5-39367985c214 # Keyline
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 50
                            10:
                              - dateAdded
                              - '2025-09-22T11:30:23+00:00'
                            11:
                              - uid
                              - 94fb3f29-9381-4491-a7ef-5cf4433d64f3
                            14:
                              - fieldUid
                              - 982e09db-7613-4a49-80ca-8e68f2f97249 # Background Colour
                        -
                          __assoc__:
                            0:
                              - type
                              - craft\fieldlayoutelements\CustomField
                            6:
                              - required
                              - false
                            7:
                              - providesThumbs
                              - false
                            8:
                              - includeInCards
                              - false
                            9:
                              - width
                              - 50
                            10:
                              - dateAdded
                              - '2025-09-24T16:24:59+00:00'
                            11:
                              - uid
                              - 1477d00a-9be1-4240-9c5e-22fddbcba422
                            14:
                              - fieldUid
                              - e7172cdd-3855-4eb8-b1f5-5ad3ea8f3a61 # Text Style
            3:
              - cardThumbAlignment
              - end
  viewMode: pane
translationKeyFormat: null
translationMethod: site
type: craft\fields\ContentBlock
