defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a6a370d2-95d3-4af2-87ca-69c7dc90de54 # About Page
handle: aboutPage
maxAuthors: 1
name: 'About Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  203be7d0-1104-40bc-88e9-d49e038b32ae: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: about.twig
    uriFormat: about
type: single
