defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 94c494ee-1756-40b0-9548-39a8b6d05a99 # Contact Page
handle: contactPage
maxAuthors: 1
name: 'Contact Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  203be7d0-1104-40bc-88e9-d49e038b32ae: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: contact.twig
    uriFormat: contact
type: single
