defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: db14e80c-4d4b-4c42-b4b9-55a78f5c0d87 # Home Page
handle: homePage
maxAuthors: 1
name: 'Home Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  203be7d0-1104-40bc-88e9-d49e038b32ae: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
