defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 7c1b229f-c54a-435e-be12-8fea7ceed3a0 # Page
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  203be7d0-1104-40bc-88e9-d49e038b32ae: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: page.twig
    uriFormat: '{slug}'
type: channel
