defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 166cfb30-28b6-494f-bd52-e27b2fdb91a1 # Project
handle: projects
maxAuthors: 1
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  203be7d0-1104-40bc-88e9-d49e038b32ae: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry.twig
    uriFormat: 'projects/{slug}'
type: channel
