defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: fe38ad5f-99d7-4208-9d80-897398c634f9 # Project Page
handle: projectPage
maxAuthors: 1
name: 'Project Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  203be7d0-1104-40bc-88e9-d49e038b32ae: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: projects/index.twig
    uriFormat: projects
type: single
