defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9977292a-e6b7-4791-90d9-8a01a62c72fa # Services Page
handle: servicesPage
maxAuthors: 1
name: 'Services Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  203be7d0-1104-40bc-88e9-d49e038b32ae: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: services/index.twig
    uriFormat: services
type: single
