defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6e351bb8-a856-44c1-bb5d-94a25b720dc2 # Team Member
handle: teamMemberrs
maxAuthors: 1
name: 'Team Memberrs'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  203be7d0-1104-40bc-88e9-d49e038b32ae: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
