defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 66cbddfe-d477-4f4f-acb1-64401a8b2bf5 # Testimonials
handle: testimonials
maxAuthors: 1
name: Testimonials
propagationMethod: all
siteSettings:
  203be7d0-1104-40bc-88e9-d49e038b32ae: # $CRAFT_SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
